services:
  websocket-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    depends_on:
      - websocket-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  k6:
    image: loadimpact/k6
    volumes:
      - ./test.js:/test/test.js
    depends_on:
      - websocket-app
      - influxdb
    command: run --out influxdb=http://influxdb:8086/k6 /test/test.js
    networks:
      - app-network

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    networks:
      - app-network
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - app-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
